"""Document Drafting Handbook-conformant skeleton templates.

Inputs: one part's authority record plus a model-generated narrative.
Outputs: a plain-text NPRM or final-rule skeleton whose structure comes from
the DDH (Aug 2018 ed., rev. 2.2 — snapshotted under ``data/raw``) and whose
substance is either gate-verified set-out text or a visible placeholder.
Failure mode: none here — this module is deterministic string assembly; all
rejection logic lives in ``conformance.py`` (fail-closed there).

The generator produces STRUCTURE; the human produces SUBSTANCE
(EXTEND-OGC01 Stage 3.3). Every required analysis renders as a visible
placeholder block. The skeleton never names an issuing agency, invents a
docket/RIN/contact/date, or proposes any substantive amendment.
"""

from reglens.authority.records import PartAuthority

PLACEHOLDER = "[PLACEHOLDER — attorney to complete]"

# DDH-required preamble captions, in required order.
PREAMBLE_CAPTIONS: tuple[str, ...] = (
    "AGENCY:",
    "ACTION:",
    "SUMMARY:",
    "DATES:",
    "ADDRESSES:",
    "FOR FURTHER INFORMATION CONTACT:",
    "SUPPLEMENTARY INFORMATION:",
)

# Required-analysis sections stubbed (never fabricated) per Stage 3.2. The
# E.O. 14192 stub mirrors the field structure of reginfo.gov's "Table 1.
# 14192 actions and costs/cost-savings by agency" (snapshotted PDF) — no
# xlsx workbook exists, so the in-PDF table's fields are the template.
ANALYSIS_SECTIONS: tuple[str, ...] = (
    "Regulatory Flexibility Act",
    "Congressional Review Act",
    "Executive Order 12866 (Regulatory Planning and Review)",
    "Paperwork Reduction Act",
    "Unfunded Mandates Reform Act",
    "Executive Order 14192 (Regulatory Cost Offset Accounting)",
)

_EO14192_STUB = f"""      Classification of this action (regulatory / deregulatory): {PLACEHOLDER}
      Offsetting actions identified: {PLACEHOLDER}
      Present-value costs or cost savings (by agency, per the E.O. 14192
      accounting method): {PLACEHOLDER}"""

DOC_TYPES = {
    "nprm": ("Notice of proposed rulemaking.", "proposes to amend"),
    "final": ("Final rule.", "amends"),
}


def build_skeleton(
    record: PartAuthority,
    doc_type: str,
    summary: str,
    supplementary_intro: str,
) -> str:
    """Assemble one skeleton. ``summary``/``supplementary_intro`` are the
    model-generated narrative (labeled as such in the output)."""
    action_line, amend_verb = DOC_TYPES[doc_type]
    part = record.part
    sections = [
        f"   {index}. {name}\n\n" + (_EO14192_STUB if "14192" in name else f"      {PLACEHOLDER}")
        for index, name in enumerate(ANALYSIS_SECTIONS, start=3)
    ]
    analysis_block = "\n\n".join(sections)
    return f"""DRAFT SKELETON — generated by RegLens-31 (independent technical demonstration).
This is NOT a Federal Register document, is not from any agency, and contains
no agency position. Model-generated narrative fields are marked. All required
analyses are placeholders for attorney completion.

Billing code: {PLACEHOLDER}

31 CFR Part {part}

[Docket number]: {PLACEHOLDER}
[RIN]: {PLACEHOLDER}

AGENCY: {PLACEHOLDER}

ACTION: {action_line}

SUMMARY: [model-generated] {summary}

DATES: {PLACEHOLDER}

ADDRESSES: {PLACEHOLDER}

FOR FURTHER INFORMATION CONTACT: {PLACEHOLDER}

SUPPLEMENTARY INFORMATION:

   I. Background

   [model-generated] {supplementary_intro}

   {PLACEHOLDER}

   II. Section-by-Section Analysis

      {PLACEHOLDER}

{analysis_block}

List of Subjects in 31 CFR Part {part}

   {PLACEHOLDER}

Words of Issuance and Amendatory Instructions

For the reasons set forth in the preamble, {PLACEHOLDER} {amend_verb}
31 CFR part {part} as follows:

{record.part_heading}

1. The authority citation for part {part} continues to read as follows:

   {record.authority_text}

2. {PLACEHOLDER} Amend § {part}.___ as follows: {PLACEHOLDER}

Signature block: {PLACEHOLDER}
"""
