/**
 * Live-draft assembly + the in-browser subset of the conformance gate.
 *
 * The deterministic skeleton comes from the build-time exporter
 * (`/data/draft-templates/…`, generated by the same Python template as the
 * committed drafts); the live model narrative is spliced into two sentinel
 * slots and the result is checked by a TypeScript subset of the Python gate:
 * heading order, placeholder integrity, fabrication scan, and verbatim
 * quote verification against the shipped part text. `normalizeForGate`
 * mirrors `reglens/provenance.py` (per-character NFKC, whitespace runs
 * collapsed, ends trimmed) the same way `search-utils.ts` twins the Python
 * tokenizer. Checks that need the full Python corpus (set-out text against
 * cited U.S.C. sections) are not reproduced here — the UI labels the result
 * as the live subset, never as the full build-time gate.
 *
 * Failure mode: fail-visible — a failed check is reported to the reader
 * beside the output rather than silently accepted.
 */

export const MODEL_SUMMARY_SLOT = "[[MODEL-SUMMARY]]";
export const MODEL_SUPPLEMENTARY_SLOT = "[[MODEL-SUPPLEMENTARY]]";
export const PLACEHOLDER = "[PLACEHOLDER — attorney to complete]";

// DDH-required preamble captions, in required order (templates.py).
const PREAMBLE_CAPTIONS = [
  "AGENCY:",
  "ACTION:",
  "SUMMARY:",
  "DATES:",
  "ADDRESSES:",
  "FOR FURTHER INFORMATION CONTACT:",
  "SUPPLEMENTARY INFORMATION:",
] as const;

const ANALYSIS_SECTIONS = [
  "Regulatory Flexibility Act",
  "Congressional Review Act",
  "Executive Order 12866 (Regulatory Planning and Review)",
  "Paperwork Reduction Act",
  "Unfunded Mandates Reform Act",
  "Executive Order 14192 (Regulatory Cost Offset Accounting)",
] as const;

// Fabrication patterns ported from conformance.py — applied to the
// model-generated narrative only.
const FABRICATION_PATTERNS: ReadonlyArray<readonly [string, RegExp]> = [
  ["rin", /\bRIN\s*\d{4}-[A-Z]{2}\d{2}\b/],
  ["docket-id", /\b[A-Z]{2,10}-\d{4}-\d{3,}\b/],
  ["dollar-amount", /\$\s?\d/],
  ["phone", /(?:\(\d{3}\)\s?|\b\d{3}[-.])\d{3}[-.]\d{4}\b/],
  ["email", /[\w.+-]+@[\w-]+\.[A-Za-z]{2,}/],
  [
    "calendar-date",
    /\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}\b|\b\d{4}-\d{2}-\d{2}\b/,
  ],
  ["url", /https?:\/\/|\bwww\.[\w-]+\.\w{2,}/i],
];

const QUOTE_FOLD: Record<string, string> = { "‘": "'", "’": "'", "“": '"', "”": '"' };
const QUOTED_STRING = /"([^"]{15,})"|'([^']{15,})'/g;

/** Mirror of reglens/provenance.py normalization (documented divergence: JS \s). */
export function normalizeForGate(text: string): string {
  const out: string[] = [];
  let pendingSpace = false;
  for (const char of text) {
    for (const normalizedChar of char.normalize("NFKC")) {
      if (/\s/.test(normalizedChar)) {
        pendingSpace = true;
        continue;
      }
      if (pendingSpace) {
        if (out.length > 0) out.push(" ");
        pendingSpace = false;
      }
      out.push(normalizedChar);
    }
  }
  return out.join("");
}

/** True iff the quote's normalized form is an exact substring of the source's. */
export function verifyQuoteAgainst(sourceText: string, quote: string): boolean {
  const normalizedQuote = normalizeForGate(quote);
  if (normalizedQuote.length === 0) return false;
  return normalizeForGate(sourceText).includes(normalizedQuote);
}

function foldQuotes(text: string): string {
  return text.replace(/[‘’“”]/g, (c) => QUOTE_FOLD[c] ?? c);
}

/** Names of fabrication patterns found in the model narrative. */
export function scanFabrication(narrative: string): string[] {
  const folded = foldQuotes(narrative);
  return FABRICATION_PATTERNS.filter(([, pattern]) => pattern.test(folded)).map(([name]) => name);
}

/** Count quoted strings (≥15 chars) that fail verification against the part text. */
export function countUnverifiedQuotes(narrative: string, partText: string): number {
  const folded = foldQuotes(narrative);
  let unverified = 0;
  for (const match of folded.matchAll(QUOTED_STRING)) {
    const quote = match[1] ?? match[2] ?? "";
    if (!verifyQuoteAgainst(partText, quote)) unverified += 1;
  }
  return unverified;
}

/** Splice the live narrative into the exported skeleton (both slots exactly once). */
export function assembleSkeleton(
  template: string,
  summary: string,
  supplementaryIntro: string,
): string {
  if (
    template.split(MODEL_SUMMARY_SLOT).length !== 2 ||
    template.split(MODEL_SUPPLEMENTARY_SLOT).length !== 2
  ) {
    throw new Error("draft template is missing its narrative slots");
  }
  return template
    .replace(MODEL_SUMMARY_SLOT, summary)
    .replace(MODEL_SUPPLEMENTARY_SLOT, supplementaryIntro);
}

export interface LiveDraftChecklist {
  headings_in_order: boolean;
  analysis_sections_present: boolean;
  placeholders_intact: boolean;
  narrative_fabrication_clean: boolean;
  quotes_verified: boolean;
  fabrication_hits: string[];
  unverified_quote_count: number;
  passed: boolean;
}

/** The in-browser subset of check_draft (conformance.py) for a live draft. */
export function checkLiveDraft(
  assembled: string,
  narrativeText: string,
  partText: string,
): LiveDraftChecklist {
  const positions = PREAMBLE_CAPTIONS.map((caption) => assembled.indexOf(caption));
  const headingsInOrder =
    positions.every((p) => p >= 0) && positions.every((p, i) => i === 0 || p > positions[i - 1]);
  const analysisSectionsPresent = ANALYSIS_SECTIONS.every((name) => assembled.includes(name));
  // Each analysis section window runs to the NEXT section (or List of
  // Subjects) so a neighboring placeholder can never satisfy a filled stub.
  const boundaries = [...ANALYSIS_SECTIONS, "List of Subjects"];
  let placeholdersIntact = true;
  for (let i = 0; i < ANALYSIS_SECTIONS.length; i += 1) {
    const index = assembled.indexOf(ANALYSIS_SECTIONS[i]);
    if (index < 0) {
      placeholdersIntact = false;
      break;
    }
    const nextIndex = assembled.indexOf(boundaries[i + 1], index + ANALYSIS_SECTIONS[i].length);
    const windowText = assembled.slice(index, nextIndex > index ? nextIndex : assembled.length);
    if (!windowText.includes(PLACEHOLDER)) {
      placeholdersIntact = false; // fail-closed: a silently filled stub is a defect
      break;
    }
  }
  const fabricationHits = scanFabrication(narrativeText);
  const unverifiedQuoteCount = countUnverifiedQuotes(narrativeText, partText);
  const checklist: LiveDraftChecklist = {
    headings_in_order: headingsInOrder,
    analysis_sections_present: analysisSectionsPresent,
    placeholders_intact: placeholdersIntact,
    narrative_fabrication_clean: fabricationHits.length === 0,
    quotes_verified: unverifiedQuoteCount === 0,
    fabrication_hits: fabricationHits,
    unverified_quote_count: unverifiedQuoteCount,
    passed: false,
  };
  checklist.passed =
    checklist.headings_in_order &&
    checklist.analysis_sections_present &&
    checklist.placeholders_intact &&
    checklist.narrative_fabrication_clean &&
    checklist.quotes_verified;
  return checklist;
}

export interface LiveDraftSuccess {
  ok: true;
  summary: string;
  supplementary_intro: string;
  model: string;
}

export interface LiveDraftFailure {
  ok: false;
  status: number;
  error: string;
  rateLimited: boolean;
}

/** POST to the same-origin live endpoint; every failure is typed, never thrown. */
export async function requestLiveDraft(
  part: number,
  docType: string,
  policyGoal: string,
): Promise<LiveDraftSuccess | LiveDraftFailure> {
  let response: Response;
  try {
    response = await fetch("/api/draft", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(
        policyGoal.trim().length > 0
          ? { part, doc_type: docType, policy_goal: policyGoal.trim() }
          : { part, doc_type: docType },
      ),
    });
  } catch {
    return { ok: false, status: 0, error: "the live endpoint is unreachable", rateLimited: false };
  }
  let payload: unknown = null;
  try {
    payload = await response.json();
  } catch {
    // fall through — a non-JSON error body still yields a typed failure below
  }
  const record = (payload ?? {}) as Record<string, unknown>;
  if (!response.ok) {
    return {
      ok: false,
      status: response.status,
      error: typeof record.error === "string" ? record.error : "live generation failed",
      rateLimited: response.status === 429,
    };
  }
  const summary = record.summary;
  const supplementaryIntro = record.supplementary_intro;
  const model = record.model;
  if (
    typeof summary !== "string" ||
    typeof supplementaryIntro !== "string" ||
    typeof model !== "string"
  ) {
    return { ok: false, status: response.status, error: "malformed response", rateLimited: false };
  }
  return { ok: true, summary, supplementary_intro: supplementaryIntro, model };
}
